### ISSUE TITLE
Does not compile on Mac. Nix fails after downloading 1.6 GB of useless dependencies.

### ISSUE THREAD

**Issue by Maddimax** [arximboldi/ewig#15]
Even after adding "{ allowBroken = true; }" to ~/.config/nixpkgs/config.nix

It still fails with:

`
~/p/a/ewig ❯❯❯ nix-shell                                                                                                                                                    

these derivations will be built:
  /nix/store/0h9s3khp2d47zkw12rngvajxcny1mn1c-libhttpserver-4895f43ed29195af70beb47bcfd1ef3ab4555665-src.drv
  /nix/store/0nm92fbdqm59gsr2il5c2c5fyvfvs52y-cereal-f158a44a3277ec2e1807618e63bcb8e1bd559649-src.drv
  /nix/store/bi4si352yncwl9r7hmrv0ympr2rnrl83-libmicrohttpd-0.9.55.drv
  /nix/store/4iqxirzzyc2wq12jdm4jxm37xxdmkfbm-libhttpserver-git-4895f43ed29195af70beb47bcfd1ef3ab4555665.drv
  /nix/store/5pkfxzl7c9k5pwk5wsdr2yy4gig1pfic-utfcpp-67036a031d131b5a929a525677e4356850fa4e37-src.drv
  /nix/store/7710a7xm9db626x2zcygv6g9k4z319nr-lager-86a2f39ae2f753a91eb22badc2bfcd2663654dfa-src.drv
  /nix/store/a3p9580l9njw8ix88wzmc660g0q3958n-utfcpp-git-67036a031d131b5a929a525677e4356850fa4e37.drv
  /nix/store/akckwqwq73gr2mpnck9y1ki52hcsx7ns-immer-2885357e5fc9fba171c4613f1841591af9e31cf1-src.drv
  /nix/store/zif8s23ngnjbbcg86wc2vzpsx79z1j0f-scelta-bd121843e227435f8f55c4aaf7e2de536f05b583-src.drv
  /nix/store/ibmg55yg9hfvfd2kj6vhmdf1bdd2cg6h-scelta-git-bd121843e227435f8f55c4aaf7e2de536f05b583.drv
  /nix/store/lrbcnkvi5dmrpcgd276avvmpk1sw4r3a-immer-git-2885357e5fc9fba171c4613f1841591af9e31cf1.drv
  /nix/store/m2f4gaizap8k53pbyy1v7dzsa9b3afqm-cereal-git-arximboldi-f158a44a3277ec2e1807618e63bcb8e1bd559649.drv
  /nix/store/yc3pvldgmvqv9jh0ix4mf8pg66mi8qjc-lager.drv
building '/nix/store/akckwqwq73gr2mpnck9y1ki52hcsx7ns-immer-2885357e5fc9fba171c4613f1841591af9e31cf1-src.drv'...
dyld: Library not loaded: /usr/lib/system/libsystem_network.dylib
  Referenced from: /nix/store/zdh6jqgv3ayqgl0ifj1z3f9n4s31d8s4-Libsystem-osx-10.11.6/lib/libSystem.B.dylib
  Reason: image not found
builder for '/nix/store/akckwqwq73gr2mpnck9y1ki52hcsx7ns-immer-2885357e5fc9fba171c4613f1841591af9e31cf1-src.drv' failed due to signal 6 (Abort trap: 6)
building '/nix/store/0nm92fbdqm59gsr2il5c2c5fyvfvs52y-cereal-f158a44a3277ec2e1807618e63bcb8e1bd559649-src.drv'...
cannot build derivation '/nix/store/lrbcnkvi5dmrpcgd276avvmpk1sw4r3a-immer-git-2885357e5fc9fba171c4613f1841591af9e31cf1.drv': 1 dependencies couldn't be built
error: build of '/nix/store/a3p9580l9njw8ix88wzmc660g0q3958n-utfcpp-git-67036a031d131b5a929a525677e4356850fa4e37.drv', '/nix/store/ibmg55yg9hfvfd2kj6vhmdf1bdd2cg6h-scelta-git-bd121843e227435f8f55c4aaf7e2de536f05b583.drv', '/nix/store/lrbcnkvi5dmrpcgd276avvmpk1sw4r3a-immer-git-2885357e5fc9fba171c4613f1841591af9e31cf1.drv', '/nix/store/yc3pvldgmvqv9jh0ix4mf8pg66mi8qjc-lager.drv' failed
`

**Comment by arximboldi** [comment]
Ooops! I just need to upgrade the pinned `<nixpkgs>` version, since the one we are using exhibits that problem on MacOs Mojave, which I guess you are using. If you recently installed Nix, just trying this might work:
```
nix-shell --arg nixpkgs <nixpkgs>
```
This will use the `nixpkgs` repository already installed in the system. If you installed Nix recently, probably it has the `libsystem` issue already fixed. It should work, but I can't be 100% confident. Feel free to report any further problems with that.

Another option is to just avoid Nix and install cmake, boost, immer, cereal and ncurses manually. That might be more effort.

I understand that Nix might doewnload more dependencies that seem necessary. However, thanks to Nix with a pinned Nixpkgs I can get consistent results in different systems and CI and development environments. Sadly, as you found out, this is only 99% the case on MacOs, since it is a proprietary OS and Nix is forced to depend on "inpure" parts of the underlying system, that change with different OS versions.

Let me know if you have any other problems and if there is anything I can do to help! I have an old Mac laptop that I rarely use that I can try to upgrade to Mojave and reproduce and fix the issue there. I am quite busy this week so it can take a few days though. Thank you for your patience!

**Comment by arximboldi** [comment]
Also, if you are considering using this or Immer in a commercial project, please consider sponsoring the project so I can add new features and keep high quality maintenance. You can do so via Patreon or send me an email to juanpe@sinusoid.al for custom sponsorship or consulting deals :smile:

**Comment by Maddimax** [comment]
I tried as you said, but it fails with an error:

`~/p/a/ewig ❯❯❯ nix-shell --arg nixpkgs <nixpkgs>`
`zsh: parse error near \n`

**Comment by Maddimax** [comment]
I've managed to compile it manually after gathering all dependencies manually. I had to fix a couple of "errors" ( probably a bunch of clang / mac os x related stuff ) which I created a merge request for.

**Comment by arximboldi** [comment]
Hi @Maddimax!
I made a mistake, I think `<nixpkgs>` must be around quotes. Anyways, I two news:
1. The bad ones, I tried upgrading my Mac to Mojave but it refuses to. (Thanks Apple for the programmed obsolescence).
2. The good ones: I upgraded the Nixpkgs version, so it might work now with Nix inside Mojave.

**Comment by arximboldi** [comment]
Oh, I see! Thanks a lot :)

**Comment by Maddimax** [comment]
Afaik there is a hack to make mojave install on older Macbooks as well ;)

**Comment by arximboldi** [comment]
Aha! Coolio. Thanks!

**Comment by arximboldi** [comment]
I just merged your changes and updated the Nix formulas. Feel free to give it a try again. Cheers!

**Comment by Maddimax** [comment]
The nix-shell command works now, but there are lots of compilation errors afterwards.

**Comment by Maddimax** [comment]
[errors.txt](https://github.com/arximboldi/ewig/files/2820535/errors.txt)

**Comment by Maddimax** [comment]
^^ see attached files for errors.

**Comment by Maddimax** [comment]
( This comes after running cmake ../ && make )

**Comment by arximboldi** [comment]
I have seen those problems before... they are due to some mismatch between compiler and std librari/environment. Did you remove the contents of `build` from your previous run without Nix before running `cmake` inside the `nix-shell`? It might be that for some reason it is still picking apple clang instead of what's provided in the shell. Another option is to try `nix-shell --pure`. Another option is that I need to tweak the compiler selection on Mac.

Anyways, since it already works on Mojave, I think I might be able to reproduce this myself on older Macs. If you are tired of trying things out feel free to close the issue and I will check the compilation errors...

**Comment by Maddimax** [comment]
`nix-shell --pure` did the trick!

**Comment by arximboldi** [comment]
Awesome, thanks for looking into this!
